repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
        exclude: \.(md)$
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-json
        files: \.(json)$
      - id: check-yaml
        files: \.(yaml|yml)$
        exclude: charts/.*
  - repo: local
    hooks:
      - id: trivy
        name: trivy
        language: system
        pass_filenames: false
        entry: |
          trivy -q config --skip-files '*.hcl' --skip-dirs '**/.terragrunt-cache/*' --exit-code 1 .
  - repo: https://github.com/semgrep/pre-commit
    rev: 'v1.163.0'
    hooks:
      - id: semgrep
        entry: semgrep
