{{- if .Values.license.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.secretName }}
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ .Values.license.licenseKey | b64enc }}
{{- end }}
