{{- if and .Values.outputElasticSearch.enable .Values.outputElasticSearch.secretCreate }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "netobserv.elasticSearchCredentialsSecretName" . }}
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}
data:
  {{ .Values.outputElasticSearch.secretKeyUser }}: {{ .Values.outputElasticSearch.username | b64enc | quote }}
  {{- if not (.Values.outputElasticSearch.password | quote | empty) }}
  {{ .Values.outputElasticSearch.secretKeyPassword }}: {{ .Values.outputElasticSearch.password | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.outputOpenSearch.enable .Values.outputOpenSearch.secretCreate }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "netobserv.openSearchCredentialsSecretName" . }}
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}
data:
  {{ .Values.outputOpenSearch.secretKeyUser }}: {{ .Values.outputOpenSearch.username | b64enc | quote }}
  {{- if not (.Values.outputOpenSearch.password | quote | empty) }}
  {{ .Values.outputOpenSearch.secretKeyPassword }}: {{ .Values.outputOpenSearch.password | b64enc | quote }}
  {{- end }}
{{- end }}
