---
name: Release
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main

jobs:
  # Detect if a commit was made from a release PR with title like '[release v0.1.1] (#49)'
  release_or_pr:
    name: Release or Release PR?
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.release_or_pr.outputs.is_release }}
    steps:
      - id: release_or_pr
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          cat > /tmp/commit_message <<- EOF
          ${COMMIT_MESSAGE}
          EOF
          cat /tmp/commit_message
          # https://regex101.com/r/1z85UX/1
          echo $(grep -Pq '^\[release v(?:[0-9]{1,3}\.?){3}(?:-rc(?:\.[0-9]{1,3})?)?\] \(#[0-9]{1,5}\)$' /tmp/commit_message && echo true || echo false) > /tmp/is_release
          echo "is_release=$(cat /tmp/is_release)" >> $GITHUB_OUTPUT

  release_pr_create:
    name: Release PR create
    needs: [release_or_pr]
    if: ${{ ! fromJson(needs.release_or_pr.outputs.is_release) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Prepare Release
        id: prepare_release
        uses: elastiflow/gha-reusable/actions/prepare-release@v0
        with:
          branch: "${{ github.ref_name }}"
          changelog_update: true
          bump_version_yaml: true
          bump_version_yaml_path: charts/netobserv/Chart.yaml
          bump_version_yaml_key: '.version'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        if: ${{ fromJson(steps.prepare_release.outputs.new_release_published) }}
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "${{ github.ref_name }}"
          branch: release-from-${{ github.ref_name }}
          title: '[release v${{ steps.prepare_release.outputs.new_release_version }}]'
          body: |
            # Description
            Release the v${{ steps.prepare_release.outputs.new_release_version }} version

            # Changelog
            ${{ steps.prepare_release.outputs.new_release_notes }}

  release:
    name: Release
    needs: [release_or_pr]
    if: ${{ fromJson(needs.release_or_pr.outputs.is_release) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Prepare Release
        id: prepare_release
        uses: elastiflow/gha-reusable/actions/prepare-release@v0
        with:
          branch: "${{ github.ref_name }}"
          changelog_update: true
          bump_version_yaml: true
          bump_version_yaml_path: galaxy.yml
          bump_version_yaml_key: '.version'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
